name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, design, react ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
      working-directory: ./hello-movie
    - name: Build
      run: CI="" npm run build
      working-directory: ./hello-movie
    - name: Deploy
      run: |
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      working-directory: ./hello-movie
      env: |
        github_token: ${{ secrets.ACTION_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
